AddonId: Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad
Packages:
  - Version: 1.0
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.0/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_0.pthm
    Changelog:
      - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-29
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.1/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_1.pthm
    Changelog:
      - 'Add border to windows'
      - 'Changed text color of links in game description'
      - 'Details View: Add option in ThemeModifier extension to disable game background image blur'
      - 'Details View: Adjustments background image darkening and noise layers'
      - 'NotificationMessage: Decrease font weight'
      - 'SearchView style changes'
  - Version: 1.2
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-31
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.2/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_2.pthm
    Changelog:
      - 'Animate popups and menus opacity and offsets when they are opened'
      - 'Details View: Disable game background image blur by default. Can be enabled with option in ThemeModifier extension.'
      - 'Details View: Prevent window background image from being displayed when Details View is active. Only the Details View background image setting can be displayed now.'
      - 'Fix textbox background in filters popups not being visible'
      - 'Fix window background noise layer not applying on non library views'