AddonId: Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad
Packages:
  - Version: 1.0
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.0/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_0.pthm
    Changelog:
      - 'Initial release'