AddonId: Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad
Packages:
  - Version: 1.0
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.0/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_0.pthm
    Changelog:
      - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-29
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.1/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_1.pthm
    Changelog:
      - 'Add border to windows'
      - 'Changed text color of links in game description'
      - 'Details View: Add option in ThemeModifier extension to disable game background image blur'
      - 'Details View: Adjustments background image darkening and noise layers'
      - 'NotificationMessage: Decrease font weight'
      - 'SearchView style changes'
  - Version: 1.2
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-31
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.2/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_2.pthm
    Changelog:
      - 'Animate popups and menus opacity and offsets when they are opened'
      - 'Details View: Disable game background image blur by default. Can be enabled with option in ThemeModifier extension.'
      - 'Details View: Prevent window background image from being displayed when Details View is active. Only the Details View background image setting can be displayed now.'
      - 'Fix textbox background in filters popups not being visible'
      - 'Fix window background noise layer not applying on non library views'
  - Version: 1.3
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-08-31
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.3/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_3.pthm
    Changelog:
      - 'Details View: Fix popup animation not applying to certain items in main menu'
  - Version: 1.4
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-09-03
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.4/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_4.pthm
    Changelog:
      - 'Details View: Changed color of text of uninstalled games'
      - 'Details View: Fix Developers, Publishers and Platforms items not wrapping when they do not fit in available width'
      - 'Details View: Prevent scrolling when a button is pressed in ExtraMetadataLoader extension video player'
      - 'Grid View: Fix game details panel separator not displaying when using the DetailsToGrid ViewConverter extension'
      - 'Minor fixes'
  - Version: 1.5
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-09-08
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.5/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_5.pthm
    Changelog:
      - 'Grid View: Changed color of game selection border'
      - 'Explorer Panel: Trim text if it does not fit in available width'
      - 'Notifications: Changed background color'
  - Version: 1.6
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-10-10
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.6/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_6.pthm
    Changelog:
      - 'Add support for Play Notes extension'
      - 'Details  View: Remove text justify'
      - 'Details View: Animate background image transition if enabled in Playnite settings'
      - 'Main Window: Changed color of window buttons'
      - 'Main Window: Make minimize, maximize and close buttons icons smaller'
  - Version: 1.7
    RequiredApiVersion: 2.5.0
    ReleaseDate: 2023-10-14
    PackageUrl: https://github.com/darklinkpower/Nova-X/releases/download/1.7/Nova_X_0a95b7a3-00e4-412d-b301-f2fa3f98dfad_1_7.pthm
    Changelog:
      - 'Details View: Increase maximum value for Details View width option in ThemeModifier extension'
      - 'Details View: Remove dropshadow effect from game name'
      - 'TabControl: Make tab items borders rounded'
      - 'Window: Use rounded corners in windows and visual changes to window buttons'